{{- $rel := .Release -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: znuny
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
    {{- if .Values.podAnnotations }}
    annotations:
      {{- range .Values.podAnnotations }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      instance: {{ $rel.Namespace }}-znuny
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      labels:
        app: znuny
        service: {{ $rel.Name }}-{{ $rel.Namespace }}
        instance: {{ $rel.Namespace }}-znuny
    spec:
      containers:
        - name: znuny
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: znuny-http
              containerPort: {{ .Values.service.port }}
          {{- if .Values.resources }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          {{- else }}
          resources: {}
          {{- end }}
          {{- if or .Values.persistenVolumeClaims .Values.extraConfigmapMounts }}
          volumeMounts:
          {{- end }}
            {{- range $pvc := .Values.persistentVolumeClaims }}
            - mountPath: {{ $pvc.mount }}
              name: {{ $rel.Name }}-{{ $pvc.name }}
            {{- end }}
            {{- range $ecmm := .Values.extraConfigmapMounts }}
            - name: {{ $ecmm.name }}
              mountPath: {{ $ecmm.mountPath }}
              subPath: {{ $ecmm.subpath }}
            {{- end }}
          envFrom:
          - configMapRef:
              name: znuny-config
          - secretRef:
              name: znuny-secrets
          livenessProbe:
            httpGet:
              path: /otrs/index.pl
              port: znuny-http
            failureThreshold: 1
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /otrs/index.pl
              port: znuny-http
            failureThreshold: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - cat
                - /opt/otrs/healthy
            initialDelaySeconds: 10
            periodSeconds: 5
      hostname: {{ $rel.Name }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range $ps := .Values.image.pullSecrets }}
        - name: {{ $rel.Name }}-{{ $ps.name }}-registry-secret
        {{- end }}
      {{- end }}
      {{- if or .Values.persistentVolumeClaims .Values.extraConfigmapMounts }}
      volumes:
      {{- end }}
        {{- range $pvc := .Values.persistentVolumeClaims }}
        - name: {{ $rel.Name }}-{{ $pvc.name }}
          persistentVolumeClaim:
            claimName: {{ $rel.Name }}-{{ $pvc.name }}
        {{- end }}
        {{- range $ecmm := .Values.extraConfigmapMounts }}
        - name: {{ $ecmm.name }}
          configMap:
            name: {{ $ecmm.configMap }}
        {{- end }}


