---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-znuny
  namespace: {{ .Release.Namespace }}
  labels:
    app: znuny
    service: {{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  ports:
    - name: "{{ .Values.service.port }}"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    instance: {{ .Release.Name }}-{{ .Release.Namespace }}-znuny


