{{- $rel := .Release -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: znuny-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: znuny
    service: {{ .Release.Name }}-{{ .Release.Namespace }}
data:
  {{- if .Values.config.logs.path }}
  ZNUNY_LOGS_PATH: {{ .Values.config.logs.path }}
  {{- end }}
  ZNUNY_DATABASE_TYPE: {{ .Values.config.database.type }}
  ZNUNY_DATABASE_HOST: {{ .Values.config.database.host | default (printf "%s-postgresql.%s.svc.cluster.local" $rel.Name $rel.Namespace) }}
  ZNUNY_DATABASE_PORT: {{ .Values.config.database.port | quote }}
  ZNUNY_DATABASE_NAME: {{ .Values.config.database.name }}
  ZNUNY_DATABASE_USER: {{ .Values.config.database.user }}
  ZNUNY_APACHE_DOMAIN: {{ .Values.config.apache.domain | default "znuny.domain.tld" }}
{{- if .Values.config.apache.rewriteRules }}
  ZNUNY_APACHE_REWRITE_RULES: |-
{{- .Values.config.apache.rewriteRules | nindent 4 }}
{{- end }}
  ZNUNY_USER_ADMIN_NAME: {{ .Values.config.users.admin.name }}
{{- if eq .Values.config.mails.type "external" }}
  ZNUNY_MAILING_TYPE: {{ .Values.config.mails.type }}
  ZNUNY_MAILING_HOST: {{ .Values.config.mails.host }}
  ZNUNY_MAILING_PORT: {{ .Values.config.mails.port | quote }}
  ZNUNY_MAILING_USER: {{ .Values.config.mails.user }}
{{- else if eq .Values.config.mails.type "internal" }}
  ZNUNY_MAILING_TYPE: {{ .Values.config.mails.type }}
{{- end }}
  {{- range $index, $value := .Values.config.authentications.customers.backends }}
  ZNUNY_CUSTOMER_BACKEND_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $index, $value := .Values.config.authentications.customers.synchronizations }}
  ZNUNY_CUSTOMER_SYNCHRO_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $index, $value := .Values.config.authentications.agents.backends }}
  ZNUNY_AGENTS_BACKEND_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $index, $value := .Values.config.authentications.agents.synchronizations }}
  ZNUNY_AGENTS_SYNCHRO_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}

