{{- $rel := .Release -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: znuny-secrets
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
type: Opaque
data:
  ZNUNY_DATABASE_PASSWORD: {{ .Values.config.database.password | b64enc | quote }}
  ZNUNY_MAILS_PASSWORD: {{ .Values.config.mails.password | b64enc | quote }}
  ZNUNY_USER_ADMIN_PASSWORD: {{ .Values.config.users.admin.password | b64enc | quote }}
  {{- if .Values.config.authentications }}
  ZNUNY_AUTHENTICATIONS: {{ .Values.config.authentications | b64enc | quote }}
  {{- end }}
