{{- $rel := .Release -}}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-postgresql-secrets
  namespace: {{ $rel.Namespace }}
  labels:
    app: postgresql
    service: {{ $rel.Name }}
type: Opaque
data:
  postgres_password: {{ .Values.postgresql.config.password | b64enc | quote }}
{{- end }}