{{- $rel := .Release -}}
{{- if not .Values.config.database.externalSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-database-credentials
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
type: Opaque
data:
  ZNUNY_DATABASE_USER: {{ .Values.config.database.username | default "" | b64enc | quote }}
  ZNUNY_DATABASE_PASSWORD: {{ .Values.config.database.password | default "" | b64enc | quote }}
{{- end }}
