{{- $rel := .Release -}}
{{- if and (not .Values.config.authentications.externalSecret) .Values.config.authentications.backends }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-authentications-backends
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
type: Opaque
data:
  ZNUNY_AUTHENTICATIONS_BACKENDS: {{ .Values.config.authentications.backends | default "" | b64enc | quote }}
{{- end }}
