{{- $rel := .Release -}}
{{- if and (not .Values.config.mails.smtp.externalSecret) .Values.config.mails.smtp.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-smtp-credentials
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
type: Opaque
data:
  ZNUNY_MAILING_USER: {{ .Values.config.mails.smtp.username | default "" | b64enc | quote }}
  ZNUNY_MAILING_PASSWORD: {{ .Values.config.mails.smtp.password | default "" | b64enc | quote }}
{{- end }}
