{{- $rel := .Release -}}
{{- if not .Values.config.users.admin.externalSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-users-admin-credentials
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
type: Opaque
data:
  ZNUNY_USER_ADMIN_NAME: {{ .Values.config.users.admin.username | default "root@localhost" | b64enc | quote }}
  ZNUNY_USER_ADMIN_PASSWORD: {{ .Values.config.users.admin.password | default (randAlphaNum 20) | b64enc | quote }}
{{- end }}
