{{- $rel := .Release -}}
{{- if and .Values.config.api.healthstatus.apiKey (not .Values.config.api.healthstatus.externalSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-api-credentials
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}-{{ $rel.Namespace }}
type: Opaque
data:
  ZNUNY_HEALTHSTATUS_APIKEY: {{ .Values.config.api.healthstatus.apiKey | b64enc | quote }}
{{- end }}
