# Default values for znuny-helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# nameOverride -- Set a name to override the release name to deploy to.
# @default -- 
nameOverride: 

# -- Set a name to override the namespace name to deploy to.
# @default -- {}
namespaceOverride: 

# -- Set a service account.
serviceAccount:

  # -- Specifies whether a service account should be created.
  # @default -- false
  create: false

  # -- Set annotations to add to the service account.
  # @default -- {}
  annotations: {}

  # -- Set he name of the service account to use.
  # @default -- "znuny"
  name: "znuny"

# -- Set the container image specifications.
image:

  # -- Set the container image to use.
  repository: ghcr.io/fr-bez-aosc/znuny

  # -- Set the image tag to use.
  tag: 6.5.8-0

  # -- Set the image pull policy.
  pullPolicy: IfNotPresent

  # -- Set a registry pull secret if a custom image hosted on a private registry is used.
  # Use it only if a pullSecret has to be created. Otherwise, use the externalPullSecrets key.
  # Both keys can be used simultaneously.
  # The secret must be encoded in base64.
  pullSecrets: []
  # pullSecrets:
  #   - name: ghcr
  #     secret: efef

  # -- Set an external registry pull secret if a custom image hosted on a private registry is used.
  # Use it only if an external pullSecret exists. Otherwise, use the pullSecrets key.
  # Both keys can be used simultaneously.
  externalPullSecrets: []
  # externalPullSecrets:
  #   - name: container-registry

# -- Set Znuny's configurations.
config:

  # -- Set the container timezone.
  timezone: Etc/UTC

  # -- Set Znuny's SysConfig secure mode.
  secureMode: true

  # -- Set the application logging.
  logs:

    # -- Set a path to Znuny's file logging.
    # The file logging is enabled only if the key "path" is set.
    path: /var/log/znuny

  # -- Set the connection of the PostgreSQL database.
  database:

    # -- Set the host of the database.
    # @section -- Required
    host:

    # -- Set the port of the database.
    # @section -- Required
    port: 5432

    # -- Set the name of the database.
    # @section -- Required
    name: znuny

    # -- Set the database username to connect to.
    # Ignored if an externalSecret is defined.
    # @section -- Required
    username:

    # -- Set the database password to connect to.
    # Ignored if an externalSecret is defined.
    # @section -- Required
    password:

    # -- Define the name of a Kubernetes secret to set the database credentials.
    # If externalSecret is defined, keys "username" and "password" will be ignored.
    # @section -- Required
    externalSecret: {}
    # externalSecret:
    #   name: znuny-database-credentials

  # -- Set Apache2 custom configurations.
  apache:
    # -- Set a local domain in Apache2 configurations.
    domain: 
    # -- Set rewrite rules in Apache2 configurations.
    rewriteRules:

      # -- Set the rewrite rules to be included.
      rules:
      # rules: |-
      #   RewriteRule ^/$ https://%{HTTP_HOST}/otrs/customer.pl
      #   RewriteRule ^/otrs/$ https://%{HTTP_HOST}/otrs/customer.pl
      #   RewriteRule ^/otrs$ https://%{HTTP_HOST}/otrs/customer.pl

      # -- Define the name of a Kubernetes configMap to set the Apache2 rewrite rules.
      # If externalConfigMap is defined, the key "rules" will be ignored.
      externalConfigMap: {}
      # externalConfigMap:
      #   name: znuny-apache-rewrite-rules

  # -- Set Znuny's local users.
  users:

    # -- Setting of the administrator user.
    admin:

      # -- Set the administrator's username.
      # Ignored if an externalSecret is defined.
      username: root@localhost

      # -- Set the administrator's password.
      # Ignored if an externalSecret is defined.
      password:

      # -- Define the name of a Kubernetes secret to set the administrator credentials.
      # If externalSecret is defined, keys "username" and "password" will be ignored.
      externalSecret: {}
      # externalSecret:
      #   name: znuny-users-admin-credentials

  # -- Set the application e-mail notifications system.
  # There are two mailing type :
  #   - sendmail: Send mail with the local sendmail module.
  #   - smtp: Connect to an external SMTP server to send mails.
  # Both features can't be activated simultaneously.
  # The feature "sendmail" will be prioritized over "smtp" as long as its "enabled" key is set to true.
  mails:

    # -- Setting of the local Sendmail module.
    sendmail:

      # -- Enable the Sendmail module.
      enabled: true

    # -- Setting of the SMTP connection.
    smtp:

      # -- Enable the SMTP connection.
      enabled: false

      # -- Set the host of the SMTP server.
      host: 

      # -- Set the port of the SMTP server.
      port: 25

      # -- Set the SMTP server username to connect to.
      # Ignored if an externalSecret is defined.
      username: 

      # -- Set the SMTP server password to connect to.
      # Ignored if an externalSecret is defined.
      password: 

      # -- Define the name of a Kubernetes secret to set the SMTP server credentials.
      # If externalSecret is defined, keys "username" and "password" will be ignored.
      externalSecret: {}
      # externalSecret:
      #   name: znuny-smtp-credentials

  # -- Set the application authentication backends.
  authentications:

    # -- Set the authentications backends configurations as following in a single block.
    backends:
    # backends: |-
    #   $Self->{CustomerUser1} = {
    #       Name => 'LDAP Data Source',
    #       Module => 'Kernel::System::CustomerUser::LDAP',
    #       Params => {
    #         Host => 'ldaps://openldap.default.svc.cluster.local',
    #         BaseDN => 'o=client,ou=People,dc=domain,dc=tld',
    #         SSCOPE => 'sub',
    #         UserDN => 'cn=znuny,ou=applications,dc=domain,dc=tld',
    #           UserPw => 'password',
    #           DestCharset => 'utf-8',
    #           SourceCharset => 'utf-8',
    #           AlwaysFilter => '',
    #           Params => {
    #               port => 686,
    #               timeout => 120,
    #               async => 0,
    #               version => 3,
    #           },
    #       },
    # (...)

    # -- Define the name of a Kubernetes secret to set the application authentication backends.
    # If externalSecret is defined, the key "backends" will be ignored.
    externalSecret: {}
    # externalSecret:
    #   name: znuny-authentication-backends

  # -- Set application extensions if enabled.
  addons:
    # -- Enable application extensions.
    enabled: false
    # -- Define packages with the format used by Znuny (e.g. 'MyRepository:Package').
    packages: []
    # packages:
    #   - https://download.znuny.org/releases/packages:Survey
    #   - https://addons.znuny.com/public:Znuny-HealthStatus

# -- Set the Kubernetes services specifications.
service:

  # -- Set the service type.
  type: ClusterIP

  # -- Set the service port.
  port: 80

# -- Set the Kubernetes ingress specifications.
ingress:

  # -- Enable the ingress features.
  enabled: false

  # -- Set the public domain on which Znuny will be exposed.
  domain:

  # -- Set annotations to add to the ingress.
  annotations: {}
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: <issuer>

  # -- Set TLS configurations.
  tls:

    # -- Enable TLS support.
    enabled: false

# -- Set persistant volumes.
# The access mode depend to your CSI
persistentVolumeClaims: []
# persistentVolumeClaims:
#   - name: "data"
#     size: "100Mi"
#     mount: "/datas"
#     accessModes:
#       - ReadWriteOnce

# -- Set Znuny's pod specifications.
pod:
  # -- Set the restart policy.
  restartPolicy: Always

  # -- Set the deployment strategy.
  deploymentStrategy: Recreate

  # -- Set replicas count.
  replicaCount: 1

  # -- Set annotations to add to Znuny's pod.
  annotations: {}
  # annotations:
  #   mykey: "myvalue"

  # -- Set labels to add to Znuny's pod.
  labels: {}
  # labels:
  #   mykey: "myvalue"

  # -- Set Znuny's container resources.
  resources:

    # -- Set Znuny's container limits.
    limits:

      # -- Set Znuny's container cpu limits.
      cpu: 2000m

      # -- Set Znuny's container memory limits.
      memory: 4096Mi

    # -- Set Znuny's container requests.
    requests:

      # -- Set Znuny's container cpu requests.
      cpu: 1000m

      # -- Set Znuny's container memory requests.
      memory: 2048Mi

  # -- Set the auto scaling of Znuny.
  autoscaling:

    # -- Enable the Horizontal pod scaling.
    enabled: false

    # -- Set the minimum of replicas.
    minReplicas: 1

    # -- Set the miximum of replicas.
    maxReplicas: 3

    # -- Set the percentage of cpu to trigger the scaling.
    targetCPUUtilizationPercentage: 80

    # -- Set the percentage of memory to trigger the scaling.
    targetMemoryUtilizationPercentage: 75

  # -- Set Znuny's pod security contexts.
  securityContext: {}
  # securityContext:
  #   # -- Set the user to run as.
  #   runAsUser: {}
  #   # -- Set the group to run as.
  #   runAsGroup: {}
  #   # -- Set the filesystem group.
  #   fsGroup: {}

# -- Set extras Kubernetes configMaps.
# @section -- Extra
extraConfigMaps: []
# extraConfigMaps:
#   # -- Set the name of the configMap.
#   - name: config-pm
#     # -- Set configMap items.
#     items:
#       # -- Set the key name.
#       - key: Config.pm
#         # -- Set the datas.
#         data: |-
#           (...)

# extraConfigmapMounts -- Set extras Kubernetes configMaps mounts.
# @section -- Extra
extraConfigmapMounts: []
    # extraConfigmapMounts.name -- Set the name of the mount.
    # - name: config-pm
    # -- Set the path to mount the configMap in the container.
    # mountPath: /opt/otrs/Kernel/Config.pm
    # -- Set the name of the configMap to use to.
    # configMap: config-pm
    # -- Set the name of the configMap key to mount as a file in the container.
    # subpath: Config.pm



  