{{- $rel := .Release -}}
{{- $val := .Values -}}
{{- if $val.znuny.image.pullSecrets -}}
{{- range $ps := $val.znuny.image.pullSecrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-{{ $ps.name }}-registry-secret
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}
type: Opaque
data:
  .dockerconfigjson: {{ $ps.secret | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}

