{{- $rel := .Release -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rel.Name }}-znuny-secrets
  namespace: {{ $rel.Namespace }}
  labels:
    app: znuny
    service: {{ $rel.Name }}
type: Opaque
data:
  ZNUNY_DATABASE_PASSWORD: {{ .Values.znuny.config.database.password | b64enc | quote }}
  ZNUNY_MAILS_PASSWORD: {{ .Values.znuny.config.mails.password | b64enc | quote }}
  ZNUNY_USER_ADMIN_PASSWORD: {{ .Values.znuny.config.users.admin.password | b64enc | quote }}
