{{- $rel := .Release -}}
{{- if .Values.znuny.jobs.upgrade.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $rel.Name }}-upgrade-job-{{ .Values.znuny.image.tag }}
  namespace: {{ $rel.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: {{ $rel.Name }}-upgrade-job
          image: {{ .Values.znuny.image.repository }}:{{ .Values.znuny.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ $rel.Name }}-znuny-config
            - secretRef:
                name: {{ $rel.Name }}-znuny-secrets
          command: ["zcli", "upgrade"]
      restartPolicy: Never
      {{- if .Values.znuny.image.pullSecrets }}
      imagePullSecrets:
        {{- range $ps := .Values.znuny.image.pullSecrets }}
        - name: {{ $rel.Name }}-{{ $ps.name }}-registry-secret
        {{- end }}
      {{- end }}
{{- end }}
