{{- $rel := .Release -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $rel.Name }}-global-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: znuny
    service: {{ .Release.Name }}-{{ .Release.Namespace }}
data:
  {{- if .Values.config.logs }}
  ZNUNY_LOGS_PATH: {{ .Values.config.logs.path }}
  {{- end }}
  ZNUNY_DATABASE_HOST: {{ .Values.config.database.host | default "localhost" }}
  ZNUNY_DATABASE_PORT: {{ .Values.config.database.port | default "5432" | quote }}
  ZNUNY_DATABASE_NAME: {{ .Values.config.database.name | default "znuny" }}
  ZNUNY_APACHE_DOMAIN: {{ .Values.config.apache.domain | default "znuny.domain.tld" }}
{{- if and .Values.config.mails.sendmail.enabled (not .Values.config.mails.smtp.enabled) }}
  ZNUNY_MAILING_TYPE: "internal"
{{- else if and .Values.config.mails.sendmail.enabled .Values.config.mails.smtp.enabled }}
  ZNUNY_MAILING_TYPE: "internal"
{{- else if and (not .Values.config.mails.sendmail.enabled) .Values.config.mails.smtp.enabled }}
  ZNUNY_MAILING_TYPE: "external"
{{- end }}
  ZNUNY_MAILING_HOST: {{ .Values.config.mails.smtp.host | default "localhost" }}
  ZNUNY_MAILING_PORT: {{ .Values.config.mails.smtp.port | default "25" | quote }}

