name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"

      - name: Install dependencies
        run: helm dependency update charts/znuny/znuny-0.1.0
  
      - name: Package chart
        run: helm package charts/znuny/znuny-0.1.0 -d ./helm

            
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: |
            ${{ github.workspace }}/helm/*.tgz
          tag_name: ${{ github.ref.tag_name}}  
          name: ${{ github.ref.tag_name}}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
