name: Release Helm chart  Workflow

on:
  push:
   branches:
     - ci 
   

jobs:
  helm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"

      - name: Install dependencies
        run: helm dependency update charts/znuny/znuny-0.1.0
  
      - name: Package chart
        run: helm package charts/znuny/znuny-0.1.0 -d . 

      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ github.actor }}"
           

      - name: Update helm index
        run: |
          helm repo index . --merge index.yaml --url https://github.com/FR-BEZ-AOSC/helm-charts/releases/download/
          git add index.yaml
          git commit -m "Update Helm repository index"
          git push origin ci
        
          

