name: Helm chart release and update index

on:
  push:
    branches:
      -  znuny-0.1.0
 

jobs:
  create-release:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"

      - name: Extract tag name from branch
        id: extract-tag
        run: echo "GIT_BRANCH=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_ENV

      - name: Install dependencies
        run: helm dependency update charts/znuny/${{env.GIT_BRANCH}}
  
      - name: Package chart
        run: helm package charts/znuny/${{env.GIT_BRANCH}} -d . 

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: |
              ${{ github.workspace }}/*.tgz
          tag_name: ${{env.GIT_BRANCH}} 
          name:  ${{env.GIT_BRANCH}}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}   


      - name: Set up Git
        run: |
            git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
            git config --global user.name "${{ github.actor }}"
            

      - name: Update helm index git
        run: |
            helm repo index . --merge index.yaml --url https://github.com/FR-BEZ-AOSC/helm-charts/releases/download/${{env.GIT_BRANCH}}
            git add index.yaml
            git commit -m "Update Helm repository index"
            git push origin ci