name: Helm chart ci Workflow

on:
  push:
    branches:
      - ci
    tags:
      - '*' 
   

jobs:
  helm:
    runs-on: ubuntu-latest
    env:
      znuny-version: 0.1.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"

      - name: Install dependencies
        run: helm dependency update charts/znuny/znuny-${{env.znuny-version}}
  
      - name: Package chart
        run: helm package charts/znuny/znuny-${{env.znuny-version}} -d . 

      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ github.actor }}"
          

      - name: Update helm index
        run: |
              helm repo index . --merge index.yaml --url https://github.com/FR-BEZ-AOSC/helm-charts/releases/download/znuny-${{env.znuny-version}}
              git add index.yaml
              git commit -m "Update Helm repository index"
              git push origin ci
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: |
              ${{ github.workspace }}/helm/*.tgz
          tag_name: ${{ github.ref.tag_name}}  
          name: ${{ github.ref.tag_name}}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}   

