name:  Helm chart index update 

on:
  push:
   branches:
     - ci 
 
   
jobs:
  helm-index-update:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"
      - name: Set up Git
        run: |
            git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
            git config --global user.name "${{ github.actor }}"
            

      - name: Update helm index git
        run: |   
            git add index.yaml
            git commit -m "Update Helm repository index"
            git push origin ci