name:  Helm chart index update 

on:
  push:
   branches:
     - ci 
   
jobs:
  helm-index-update:
    runs-on: ubuntu-latest
    env:
      znuny-version: 0.1.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"
      - name: Set up Git
        run: |
            git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
            git config --global user.name "${{ github.actor }}"
            

      - name: Update helm index
        run: |
            helm repo index . --merge index.yaml --url https://github.com/FR-BEZ-AOSC/helm-charts/releases/download/znuny-${{env.znuny-version}}
            git add index.yaml
            git commit -m "Update Helm repository index"
            git push origin ci